# Generated by Django 3.1.3 on 2020-11-04 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='profession',
            new_name='professions',
        ),
    ]
